services:
  - type: web
    name: student-leaderboard-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false

  - type: web
    name: student-leaderboard-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
